GET http://localhost:5001/users
################################
GET http://localhost:5001/user/2
################################
POST http://localhost:5001/user
Content-Type: application/json

{
    "name": "studentr",
    "email": "mp@mail.com",
    "password": "studentr",
    "gender": "Female",
    "role": "student",
    "status": "redovni"
}

################################
PUT http://localhost:5001/user/6
Content-Type: application/json

{
    "name": "Mate Matic",
    "email": "mt@mail.com",
    "password": "Mate",
    "gender": "Male",
    "role": "student",
    "status": "redovni"
}
################################
DELETE  http://localhost:5001/user/10

################################
///COURSES

GET http://localhost:5001/courses
################################
GET http://localhost:5001/course/1
################################
POST http://localhost:5001/course
Content-Type: application/json

{
    
    "ime": "Digitalna",
    "kod": "SIT002",
    "program": "Program nije unesen",
    "bodovi": 5,
    "semestar_redovni": 6,
    "semestar_izvanredni": 3,
    "izborni": "ne",
    "createdAt": "2022-09-05T19:38:46.985Z",
    "updatedAt": "2022-09-05T19:38:46.985Z"
}

################################
PUT http://localhost:5001/course/2
Content-Type: application/json

{
  "ime": "test",
    "kod": "SIT001",
    "program": "Program nije unesen",
    "bodovi": 5,
    "semestar_redovni": 1,
    "semestar_izvanredni": 1,
    "izborni": "ne",
}
################################
DELETE  http://localhost:5001/course/10


###########

GET http://localhost:5001/enrollments
###
###getenrollmentbyCourseId
GET http://localhost:5001/enrollment/1
###

################################

POST http://localhost:5001/enrollment
Content-Type: application/json

{

    "userid": "1",
    "courseid": "3",
    "status": "Polozio",

}

###########

GET http://localhost:5001/enrollmentCourse/2
###
###getenrollmentbyCourseId
GET http://localhost:5001/enrollmentUser/2
###